### ISSUE TITLE
Pass@1指标

### ISSUE THREAD

**Issue by NTDXYG** [jiafeng0527/dataset_extract#2]
请问这个数据集带有测试用例，可以用pass@1评估吗？

**Comment by 2726fj** [comment]
不能直接使用pass@1来进行评估，因为函数中存在外部依赖。因此，运行函数需要成功部署相应的代码仓库，这个过程可能有一定难度。不过，如果你对此感兴趣，我们非常欢迎你进行尝试，我们也很乐意提供协助！
